# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# ============================================================================
# Entra ID App Registration Module
# ============================================================================

data "azurerm_client_config" "current" {}

# Generate UUIDs for OAuth2 scope and app role
resource "random_uuid" "oauth2_scope_id" {}
resource "random_uuid" "app_role_id" {}

# ============================================================================
# Entra ID App Registration for JWT Authentication
# ============================================================================

resource "azuread_application" "gateway_app" {
  display_name     = "${var.naming_prefix}-app"
  owners           = [data.azurerm_client_config.current.object_id]
  sign_in_audience = "AzureADMyOrg"

  # Start with empty identifier_uris - actual URI set by separate resource after client_id is generated
  identifier_uris = []

  # Required resource access (if the gateway needs to call other APIs)
  required_resource_access {
    resource_app_id = "00000003-0000-0000-c000-000000000000" # Microsoft Graph

    resource_access {
      id   = "e1fe6dd8-ba31-4d61-89e7-88639da4683d" # User.Read
      type = "Scope"
    }
  }

  api {
    mapped_claims_enabled          = false
    requested_access_token_version = 2

    oauth2_permission_scope {
      admin_consent_description  = "Allow access to Unified AI Gateway API"
      admin_consent_display_name = "Access Unified AI Gateway API"
      enabled                    = true
      id                         = random_uuid.oauth2_scope_id.result
      type                       = "User"
      user_consent_description   = "Allow access to Unified AI Gateway API"
      user_consent_display_name  = "Access Unified AI Gateway API"
      value                      = "access_as_user"
    }
  }

  app_role {
    allowed_member_types = ["User", "Application"]
    description          = "ReadWrite roles have read and write access to the application data"
    display_name         = "ReadWrite"
    enabled              = true
    id                   = random_uuid.app_role_id.result
    value                = "Task.ReadWrite"
  }

  lifecycle {
    # Ignore changes to identifier_uris after creation to prevent drift
    ignore_changes = [identifier_uris]
  }
}

# Set identifier URI using separate resource after app is created
# This approach ensures the client_id is available before setting the URI
resource "azuread_application_identifier_uri" "gateway_app_uri" {
  application_id = azuread_application.gateway_app.id
  identifier_uri = "api://${azuread_application.gateway_app.client_id}"
  depends_on = [
    azuread_application.gateway_app
  ]
}

# Create service principal for the application
resource "azuread_service_principal" "gateway_sp" {
  client_id = azuread_application.gateway_app.client_id
  depends_on = [
    azuread_application.gateway_app,
    azuread_application_identifier_uri.gateway_app_uri
  ]
}

# Generate client secret for the application
resource "azuread_application_password" "gateway_app_secret" {
  application_id = azuread_application.gateway_app.id
  display_name   = "Generated by Terraform"
  depends_on = [
    azuread_application.gateway_app,
    azuread_application_identifier_uri.gateway_app_uri,
    azuread_service_principal.gateway_sp
  ]
}

# Store client secret in Key Vault
resource "azurerm_key_vault_secret" "entra_client_secret" {
  name         = "UAIG-ENTRA-APP-CLIENT-SECRET"
  value        = azuread_application_password.gateway_app_secret.value
  key_vault_id = var.key_vault_id

  depends_on = [azuread_application_password.gateway_app_secret]
}
